[workspace]
members = ["cargo:."]

[dist]
allow-dirty = ["ci"]
source-tarball = false
auto-includes = false
precise-builds = true
packages = [ "ui" ]
cargo-dist-version = "0.29.0"
ci = "github"
installers = []
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
